remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Cuthbert's Blog
description: Cuthbert is just blogging about his progress as a computer programer
