...
@import "{{ hacker.theme }}";
...

theme: jekyll-theme-hacker
title: Cuthbert's Blog
description: Bookmark this to keep an eye on my project updates!

lsi: false
safe: true
source: cuthbert86.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
